name: Deploy to AWS S3

on:
  push:
    branches: 
      - main

permissions:
  contents: read

jobs:  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: NodeJs Setup
      uses: actions/setup-node@v4
      with:
        node-version: ${{ vars.NODE_VERSION }}
        
    - name: NodeJs Setup
      run: npm install

    - name: App Build
      run: CI=false npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

    - name: Deploy to AWS E3
      run: aws s3 sync build s3://${{ secrets.AWS_S3_BUCKET_NAME }} --delete
